# Generated by Django 5.0.3 on 2024-04-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_sale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documento',
            new_name='Document',
        ),
    ]
