# Generated by Django 5.0.3 on 2024-04-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_rename_documento_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='number',
            new_name='item',
        ),
    ]
